Disable ci network testing temporarily

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -172,68 +172,68 @@ jobs:
           retention-days: 1
 
 
-  e2e-network:
-    name: "${{ matrix.name }} ${{ matrix.test }} ${{ matrix.testcase }}"
-    needs: [ verify ]
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        name: [
-          "ubuntu",
-        ]
-        test: [
-          "sshfs",
-        ]
-        testcase: [
-          "sshfs-network-dhcp",
-          "sshfs-network-static1",
-        ]
-      fail-fast: false
-    steps:
-      - name: "Prepare Node"
-        run: |
-          for m in kvm kvm-amd kvm-intel; do sudo modprobe -v "$m" ||:; done
-          test -c /dev/kvm && sudo chmod -v 666 /dev/kvm ||:
+  #e2e-network:
+  #  name: "${{ matrix.name }} ${{ matrix.test }} ${{ matrix.testcase }}"
+  #  needs: [ verify ]
+  #  runs-on: ubuntu-latest
+  #  strategy:
+  #    matrix:
+  #      name: [
+  #        "ubuntu",
+  #      ]
+  #      test: [
+  #        "sshfs",
+  #      ]
+  #      testcase: [
+  #        "sshfs-network-dhcp",
+  #        "sshfs-network-static1",
+  #      ]
+  #    fail-fast: false
+  #  steps:
+  #    - name: "Prepare Node"
+  #      run: |
+  #        for m in kvm kvm-amd kvm-intel; do sudo modprobe -v "$m" ||:; done
+  #        test -c /dev/kvm && sudo chmod -v 666 /dev/kvm ||:
 
-      - name: "Install packages"
-        run: |
-          sudo apt-get -qq -y update
-          sudo apt-get -qq -y install git qemu-kvm
+  #    - name: "Install packages"
+  #      run: |
+  #        sudo apt-get -qq -y update
+  #        sudo apt-get -qq -y install git qemu-kvm
 
-      - name: "Checkout Repository"
-        uses: actions/checkout@v4
+  #    - name: "Checkout Repository"
+  #      uses: actions/checkout@v4
 
-      - name: "Checkout submodules"
-        run: |
-          git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
-          git submodule update --init --recursive
+  #    - name: "Checkout submodules"
+  #      run: |
+  #        git submodule set-url external/busybox/upstream https://github.com/mirror/busybox
+  #        git submodule update --init --recursive
 
-      - name: "Build Sources"
-        run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} build-git
+  #    - name: "Build Sources"
+  #      run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} build-git
 
-      - name: "Build Sysimage"
-        run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} build-sysimage
+  #    - name: "Build Sysimage"
+  #      run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} build-sysimage
 
-      - name: "Build Other Tools"
-        run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} build-tools
+  #    - name: "Build Other Tools"
+  #      run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} build-tools
 
-      - name: "Run Services"
-        run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} run-services
+  #    - name: "Run Services"
+  #      run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} run-services
 
-      - name: "Boot System"
-        env:
-          QEMU_TIMEOUT: 10m
-          QEMU_MEMORY: 1G
-          QEMU_DISK_FORMAT: qcow2
-        run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} run-boot
+  #    - name: "Boot System"
+  #      env:
+  #        QEMU_TIMEOUT: 10m
+  #        QEMU_MEMORY: 1G
+  #        QEMU_DISK_FORMAT: qcow2
+  #      run: testing/testing-${{ matrix.name }}-${{ matrix.test }} test-root-${{ matrix.testcase }} run-boot
 
-      - name: "Archive Metrics"
-        uses: actions/upload-artifact@v4
-        with:
-          name: "metrics-${{ matrix.name }}-${{ matrix.test }}-${{ matrix.testcase }}"
-          path: testing/status/artifact-*.txt
-          if-no-files-found: ignore
-          retention-days: 1
+  #    - name: "Archive Metrics"
+  #      uses: actions/upload-artifact@v4
+  #      with:
+  #        name: "metrics-${{ matrix.name }}-${{ matrix.test }}-${{ matrix.testcase }}"
+  #        path: testing/status/artifact-*.txt
+  #        if-no-files-found: ignore
+  #        retention-days: 1
 
 
   metrics:
